image:
  file: .gitpod.Dockerfile

tasks:
  - init: echo 'Updating system packages...' && sudo apt-get update && sudo apt-get upgrade -y && echo 'Updating Python packages...' && pip install --upgrade pip
    command: echo 'Creating Python environment...' && conda env create -f environment.yml && echo 'Activating Python environment...' && conda activate nlp_demo && echo 'Changing to root directory...' && cd /workspace && echo 'Starting server...' && python3 -m http.server

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - github.vscode-pull-request-github
    - eamodio.gitlens
    - ms-azuretools.vscode-docker
