FROM python:3.10-slim

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    git \
    libffi-dev \
    libssl-dev \
    vim \
    procps \
    sudo \
    && rm -rf /var/lib/apt/lists/*

# Install Conda
RUN curl -o ~/miniconda.sh -O  https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh  && \
    chmod +x ~/miniconda.sh && \
    ~/miniconda.sh -b -p /opt/conda && \
    rm ~/miniconda.sh && \
    /opt/conda/bin/conda clean -ya
ENV PATH /opt/conda/bin:$PATH

# Create a non-root user
RUN adduser --disabled-password --gecos '' gitpod
RUN adduser gitpod sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
USER gitpod

# Set the working directory
WORKDIR /workspace

# Add the environment.yml file to the Docker image
ADD environment.yml /workspace/environment.yml

# Create the Conda environment
RUN conda env create -f /workspace/environment.yml
